// 本文件由 tools/gen_themes.py 生成，不要手改 —— 会被下次生成覆盖。
// 要增删主题请改 design/theme-seeds.json，然后重跑： python tools/gen_themes.py
//
// 生成时间：2026-09-13 18:26 +0800

package com.jxau.oj.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** 主题取色方式。 */
enum class ThemeMode {
    /** Android 12+ 跟随系统壁纸（Material You）。低于 12 时回落到 [DEFAULT_THEME]。 */
    FOLLOW_WALLPAPER,
    /** 使用本文件中推导好的静态色板。 */
    STATIC,
}

/**
 * 一个可选主题。
 *
 * 设置页直接用 [THEME_CATALOG] 渲染列表即可，新增主题不用改 UI 代码。
 */
data class AppTheme(
    val id: String,
    val label: String,
    val note: String,
    val mode: ThemeMode,
    /** 推导该主题色板的种子色，[ThemeMode.FOLLOW_WALLPAPER] 时为 null。 */
    val seed: String?,
)

/** 默认主题（也是 Android 12 以下回落用的那一套）。 */
val DEFAULT_THEME_ID: String = "jxau-blue"

val THEME_CATALOG: List<AppTheme> = listOf(
    AppTheme("jxau-blue", "江农蓝", "站点主色，默认主题", ThemeMode.STATIC, "#185FA5"),
    AppTheme("lake-cyan", "湖蓝", "比江农蓝更青，清爽", ThemeMode.STATIC, "#0E7490"),
    AppTheme("celadon", "青瓷", "青绿釉色，长时间看不累", ThemeMode.STATIC, "#0F6E56"),
    AppTheme("bamboo", "竹青", "偏黄的绿，与 AC 绿拉开明度", ThemeMode.STATIC, "#3B6D11"),
    AppTheme("amber", "琥珀", "暖橙黄，像台灯光", ThemeMode.STATIC, "#BA7517"),
    AppTheme("coral", "深珊瑚", "暖橙红，醒目", ThemeMode.STATIC, "#D85A30"),
    AppTheme("rosewood", "玫红", "偏深的玫色，沉稳", ThemeMode.STATIC, "#993556"),
    AppTheme("sakura", "樱粉", "浅粉，明亮通透", ThemeMode.STATIC, "#D4537E"),
    AppTheme("indigo", "靛紫", "夜间模式最舒服", ThemeMode.STATIC, "#534AB7"),
    AppTheme("violet-vivid", "紫藤", "高饱和，偏张扬", ThemeMode.STATIC, "#7C4DFF"),
    AppTheme("graphite", "石墨", "低饱和灰蓝，最不打扰", ThemeMode.STATIC, "#44546A"),
    AppTheme("monochrome", "单色", "纯灰阶，黑白印刷质感", ThemeMode.STATIC, "#4A4A4A"),
    AppTheme("contrast-blue", "高对比蓝", "对比度增强，视力不佳者友好", ThemeMode.STATIC, "#185FA5"),
    AppTheme("follow-wallpaper", "跟随壁纸", "Android 12+ 从壁纸取色，最原生的观感", ThemeMode.FOLLOW_WALLPAPER, null),
)

private val lightJxauBlue = lightColorScheme(
    primary = Color(0xFF3B608F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD4E3FF),
    onPrimaryContainer = Color(0xFF204876),
    inversePrimary = Color(0xFFA4C9FE),
    secondary = Color(0xFF545F71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD8E3F8),
    onSecondaryContainer = Color(0xFF3D4758),
    tertiary = Color(0xFF6D5677),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF6D9FF),
    onTertiaryContainer = Color(0xFF543F5E),
    background = Color(0xFFF8F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF8F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFDFE2EB),
    onSurfaceVariant = Color(0xFF43474E),
    surfaceTint = Color(0xFF3B608F),
    inverseSurface = Color(0xFF2E3035),
    inverseOnSurface = Color(0xFFEFF0F7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF73777F),
    outlineVariant = Color(0xFFC3C6CF),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF8F9FF),
    surfaceDim = Color(0xFFD9DAE0),
    surfaceContainer = Color(0xFFEDEDF4),
    surfaceContainerHigh = Color(0xFFE7E8EE),
    surfaceContainerHighest = Color(0xFFE1E2E9),
    surfaceContainerLow = Color(0xFFF2F3FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkJxauBlue = darkColorScheme(
    primary = Color(0xFFA4C9FE),
    onPrimary = Color(0xFF00315D),
    primaryContainer = Color(0xFF204876),
    onPrimaryContainer = Color(0xFFD4E3FF),
    inversePrimary = Color(0xFF3B608F),
    secondary = Color(0xFFBCC7DB),
    onSecondary = Color(0xFF263141),
    secondaryContainer = Color(0xFF3D4758),
    onSecondaryContainer = Color(0xFFD8E3F8),
    tertiary = Color(0xFFD9BDE3),
    onTertiary = Color(0xFF3D2946),
    tertiaryContainer = Color(0xFF543F5E),
    onTertiaryContainer = Color(0xFFF6D9FF),
    background = Color(0xFF111318),
    onBackground = Color(0xFFE1E2E9),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFE1E2E9),
    surfaceVariant = Color(0xFF43474E),
    onSurfaceVariant = Color(0xFFC3C6CF),
    surfaceTint = Color(0xFFA4C9FE),
    inverseSurface = Color(0xFFE1E2E9),
    inverseOnSurface = Color(0xFF2E3035),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8D9199),
    outlineVariant = Color(0xFF43474E),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF37393E),
    surfaceDim = Color(0xFF111318),
    surfaceContainer = Color(0xFF1D2024),
    surfaceContainerHigh = Color(0xFF272A2F),
    surfaceContainerHighest = Color(0xFF32353A),
    surfaceContainerLow = Color(0xFF191C20),
    surfaceContainerLowest = Color(0xFF0C0E13),
)

private val lightLakeCyan = lightColorScheme(
    primary = Color(0xFF0B6780),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB9EAFF),
    onPrimaryContainer = Color(0xFF004D62),
    inversePrimary = Color(0xFF89D0ED),
    secondary = Color(0xFF4C626B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCFE6F1),
    onSecondaryContainer = Color(0xFF354A53),
    tertiary = Color(0xFF5B5B7E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE1DFFF),
    onTertiaryContainer = Color(0xFF434465),
    background = Color(0xFFF5FAFD),
    onBackground = Color(0xFF171C1F),
    surface = Color(0xFFF5FAFD),
    onSurface = Color(0xFF171C1F),
    surfaceVariant = Color(0xFFDCE4E8),
    onSurfaceVariant = Color(0xFF40484C),
    surfaceTint = Color(0xFF0B6780),
    inverseSurface = Color(0xFF2C3134),
    inverseOnSurface = Color(0xFFEDF1F4),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF70787C),
    outlineVariant = Color(0xFFC0C8CC),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF5FAFD),
    surfaceDim = Color(0xFFD6DBDE),
    surfaceContainer = Color(0xFFEAEEF2),
    surfaceContainerHigh = Color(0xFFE4E9EC),
    surfaceContainerHighest = Color(0xFFDEE3E6),
    surfaceContainerLow = Color(0xFFF0F4F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkLakeCyan = darkColorScheme(
    primary = Color(0xFF89D0ED),
    onPrimary = Color(0xFF003544),
    primaryContainer = Color(0xFF004D62),
    onPrimaryContainer = Color(0xFFB9EAFF),
    inversePrimary = Color(0xFF0B6780),
    secondary = Color(0xFFB3CAD5),
    onSecondary = Color(0xFF1E333C),
    secondaryContainer = Color(0xFF354A53),
    onSecondaryContainer = Color(0xFFCFE6F1),
    tertiary = Color(0xFFC4C3EB),
    onTertiary = Color(0xFF2D2D4D),
    tertiaryContainer = Color(0xFF434465),
    onTertiaryContainer = Color(0xFFE1DFFF),
    background = Color(0xFF0F1416),
    onBackground = Color(0xFFDEE3E6),
    surface = Color(0xFF0F1416),
    onSurface = Color(0xFFDEE3E6),
    surfaceVariant = Color(0xFF40484C),
    onSurfaceVariant = Color(0xFFC0C8CC),
    surfaceTint = Color(0xFF89D0ED),
    inverseSurface = Color(0xFFDEE3E6),
    inverseOnSurface = Color(0xFF2C3134),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8A9296),
    outlineVariant = Color(0xFF40484C),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF353A3D),
    surfaceDim = Color(0xFF0F1416),
    surfaceContainer = Color(0xFF1B2023),
    surfaceContainerHigh = Color(0xFF252B2D),
    surfaceContainerHighest = Color(0xFF303638),
    surfaceContainerLow = Color(0xFF171C1F),
    surfaceContainerLowest = Color(0xFF0A0F11),
)

private val lightCeladon = lightColorScheme(
    primary = Color(0xFF166B54),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA4F2D5),
    onPrimaryContainer = Color(0xFF00513E),
    inversePrimary = Color(0xFF89D6BA),
    secondary = Color(0xFF4C635A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCEE9DC),
    onSecondaryContainer = Color(0xFF344C42),
    tertiary = Color(0xFF406375),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC3E8FE),
    onTertiaryContainer = Color(0xFF274B5D),
    background = Color(0xFFF5FBF6),
    onBackground = Color(0xFF171D1A),
    surface = Color(0xFFF5FBF6),
    onSurface = Color(0xFF171D1A),
    surfaceVariant = Color(0xFFDBE5DF),
    onSurfaceVariant = Color(0xFF3F4944),
    surfaceTint = Color(0xFF166B54),
    inverseSurface = Color(0xFF2C322F),
    inverseOnSurface = Color(0xFFECF2ED),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF707974),
    outlineVariant = Color(0xFFBFC9C3),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF5FBF6),
    surfaceDim = Color(0xFFD5DBD7),
    surfaceContainer = Color(0xFFE9EFEB),
    surfaceContainerHigh = Color(0xFFE4EAE5),
    surfaceContainerHighest = Color(0xFFDEE4DF),
    surfaceContainerLow = Color(0xFFEFF5F0),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkCeladon = darkColorScheme(
    primary = Color(0xFF89D6BA),
    onPrimary = Color(0xFF00382A),
    primaryContainer = Color(0xFF00513E),
    onPrimaryContainer = Color(0xFFA4F2D5),
    inversePrimary = Color(0xFF166B54),
    secondary = Color(0xFFB2CCC0),
    onSecondary = Color(0xFF1E352D),
    secondaryContainer = Color(0xFF344C42),
    onSecondaryContainer = Color(0xFFCEE9DC),
    tertiary = Color(0xFFA7CCE1),
    onTertiary = Color(0xFF0C3445),
    tertiaryContainer = Color(0xFF274B5D),
    onTertiaryContainer = Color(0xFFC3E8FE),
    background = Color(0xFF0F1512),
    onBackground = Color(0xFFDEE4DF),
    surface = Color(0xFF0F1512),
    onSurface = Color(0xFFDEE4DF),
    surfaceVariant = Color(0xFF3F4944),
    onSurfaceVariant = Color(0xFFBFC9C3),
    surfaceTint = Color(0xFF89D6BA),
    inverseSurface = Color(0xFFDEE4DF),
    inverseOnSurface = Color(0xFF2C322F),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF89938E),
    outlineVariant = Color(0xFF3F4944),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF343B37),
    surfaceDim = Color(0xFF0F1512),
    surfaceContainer = Color(0xFF1B211E),
    surfaceContainerHigh = Color(0xFF252B28),
    surfaceContainerHighest = Color(0xFF303633),
    surfaceContainerLow = Color(0xFF171D1A),
    surfaceContainerLowest = Color(0xFF0A0F0D),
)

private val lightBamboo = lightColorScheme(
    primary = Color(0xFF48672F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC8EEA8),
    onPrimaryContainer = Color(0xFF314E19),
    inversePrimary = Color(0xFFADD28E),
    secondary = Color(0xFF56624B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE7C9),
    onSecondaryContainer = Color(0xFF3F4A34),
    tertiary = Color(0xFF386665),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBBECEA),
    onTertiaryContainer = Color(0xFF1E4E4D),
    background = Color(0xFFF9FAEF),
    onBackground = Color(0xFF1A1D16),
    surface = Color(0xFFF9FAEF),
    onSurface = Color(0xFF1A1D16),
    surfaceVariant = Color(0xFFE0E4D6),
    onSurfaceVariant = Color(0xFF44483E),
    surfaceTint = Color(0xFF48672F),
    inverseSurface = Color(0xFF2E312A),
    inverseOnSurface = Color(0xFFF0F2E7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF74796D),
    outlineVariant = Color(0xFFC4C8BA),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF9FAEF),
    surfaceDim = Color(0xFFD9DBD1),
    surfaceContainer = Color(0xFFEDEFE4),
    surfaceContainerHigh = Color(0xFFE7E9DE),
    surfaceContainerHighest = Color(0xFFE2E3D9),
    surfaceContainerLow = Color(0xFFF3F5EA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkBamboo = darkColorScheme(
    primary = Color(0xFFADD28E),
    onPrimary = Color(0xFF1B3704),
    primaryContainer = Color(0xFF314E19),
    onPrimaryContainer = Color(0xFFC8EEA8),
    inversePrimary = Color(0xFF48672F),
    secondary = Color(0xFFBECBAE),
    onSecondary = Color(0xFF29341F),
    secondaryContainer = Color(0xFF3F4A34),
    onSecondaryContainer = Color(0xFFDAE7C9),
    tertiary = Color(0xFFA0CFCE),
    onTertiary = Color(0xFF003736),
    tertiaryContainer = Color(0xFF1E4E4D),
    onTertiaryContainer = Color(0xFFBBECEA),
    background = Color(0xFF11140E),
    onBackground = Color(0xFFE2E3D9),
    surface = Color(0xFF11140E),
    onSurface = Color(0xFFE2E3D9),
    surfaceVariant = Color(0xFF44483E),
    onSurfaceVariant = Color(0xFFC4C8BA),
    surfaceTint = Color(0xFFADD28E),
    inverseSurface = Color(0xFFE2E3D9),
    inverseOnSurface = Color(0xFF2E312A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF8E9286),
    outlineVariant = Color(0xFF44483E),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF373A33),
    surfaceDim = Color(0xFF11140E),
    surfaceContainer = Color(0xFF1E211A),
    surfaceContainerHigh = Color(0xFF282B24),
    surfaceContainerHighest = Color(0xFF33362F),
    surfaceContainerLow = Color(0xFF1A1D16),
    surfaceContainerLowest = Color(0xFF0C0F09),
)

private val lightAmber = lightColorScheme(
    primary = Color(0xFF845416),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCBB),
    onPrimaryContainer = Color(0xFF673D00),
    inversePrimary = Color(0xFFFABA73),
    secondary = Color(0xFF725A41),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFEDDBD),
    onSecondaryContainer = Color(0xFF58432C),
    tertiary = Color(0xFF56633B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDAE9B6),
    onTertiaryContainer = Color(0xFF3F4B26),
    background = Color(0xFFFFF8F4),
    onBackground = Color(0xFF211A14),
    surface = Color(0xFFFFF8F4),
    onSurface = Color(0xFF211A14),
    surfaceVariant = Color(0xFFF1DFD0),
    onSurfaceVariant = Color(0xFF50453A),
    surfaceTint = Color(0xFF845416),
    inverseSurface = Color(0xFF372F27),
    inverseOnSurface = Color(0xFFFDEEE3),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF827568),
    outlineVariant = Color(0xFFD4C4B5),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F4),
    surfaceDim = Color(0xFFE5D8CC),
    surfaceContainer = Color(0xFFFAEBE0),
    surfaceContainerHigh = Color(0xFFF4E6DA),
    surfaceContainerHighest = Color(0xFFEEE0D5),
    surfaceContainerLow = Color(0xFFFFF1E7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkAmber = darkColorScheme(
    primary = Color(0xFFFABA73),
    onPrimary = Color(0xFF482900),
    primaryContainer = Color(0xFF673D00),
    onPrimaryContainer = Color(0xFFFFDCBB),
    inversePrimary = Color(0xFF845416),
    secondary = Color(0xFFE0C1A3),
    onSecondary = Color(0xFF402D17),
    secondaryContainer = Color(0xFF58432C),
    onSecondaryContainer = Color(0xFFFEDDBD),
    tertiary = Color(0xFFBECC9C),
    onTertiary = Color(0xFF293411),
    tertiaryContainer = Color(0xFF3F4B26),
    onTertiaryContainer = Color(0xFFDAE9B6),
    background = Color(0xFF19120C),
    onBackground = Color(0xFFEEE0D5),
    surface = Color(0xFF19120C),
    onSurface = Color(0xFFEEE0D5),
    surfaceVariant = Color(0xFF50453A),
    onSurfaceVariant = Color(0xFFD4C4B5),
    surfaceTint = Color(0xFFFABA73),
    inverseSurface = Color(0xFFEEE0D5),
    inverseOnSurface = Color(0xFF372F27),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9D8E81),
    outlineVariant = Color(0xFF50453A),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF403830),
    surfaceDim = Color(0xFF19120C),
    surfaceContainer = Color(0xFF251E17),
    surfaceContainerHigh = Color(0xFF302921),
    surfaceContainerHighest = Color(0xFF3B332C),
    surfaceContainerLow = Color(0xFF211A14),
    surfaceContainerLowest = Color(0xFF130D07),
)

private val lightCoral = lightColorScheme(
    primary = Color(0xFF8F4C36),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBD0),
    onPrimaryContainer = Color(0xFF723521),
    inversePrimary = Color(0xFFFFB59E),
    secondary = Color(0xFF77574D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBD0),
    onSecondaryContainer = Color(0xFF5D4037),
    tertiary = Color(0xFF6B5E2F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF4E2A7),
    onTertiaryContainer = Color(0xFF52461A),
    background = Color(0xFFFFF8F6),
    onBackground = Color(0xFF231917),
    surface = Color(0xFFFFF8F6),
    onSurface = Color(0xFF231917),
    surfaceVariant = Color(0xFFF5DED7),
    onSurfaceVariant = Color(0xFF53433F),
    surfaceTint = Color(0xFF8F4C36),
    inverseSurface = Color(0xFF392E2B),
    inverseOnSurface = Color(0xFFFFEDE8),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF85736E),
    outlineVariant = Color(0xFFD8C2BC),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F6),
    surfaceDim = Color(0xFFE8D6D1),
    surfaceContainer = Color(0xFFFCEAE5),
    surfaceContainerHigh = Color(0xFFF7E4DF),
    surfaceContainerHighest = Color(0xFFF1DFDA),
    surfaceContainerLow = Color(0xFFFFF1ED),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkCoral = darkColorScheme(
    primary = Color(0xFFFFB59E),
    onPrimary = Color(0xFF561F0D),
    primaryContainer = Color(0xFF723521),
    onPrimaryContainer = Color(0xFFFFDBD0),
    inversePrimary = Color(0xFF8F4C36),
    secondary = Color(0xFFE7BDB1),
    onSecondary = Color(0xFF442A22),
    secondaryContainer = Color(0xFF5D4037),
    onSecondaryContainer = Color(0xFFFFDBD0),
    tertiary = Color(0xFFD7C68D),
    onTertiary = Color(0xFF3A3005),
    tertiaryContainer = Color(0xFF52461A),
    onTertiaryContainer = Color(0xFFF4E2A7),
    background = Color(0xFF1A110F),
    onBackground = Color(0xFFF1DFDA),
    surface = Color(0xFF1A110F),
    onSurface = Color(0xFFF1DFDA),
    surfaceVariant = Color(0xFF53433F),
    onSurfaceVariant = Color(0xFFD8C2BC),
    surfaceTint = Color(0xFFFFB59E),
    inverseSurface = Color(0xFFF1DFDA),
    inverseOnSurface = Color(0xFF392E2B),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFFA08C87),
    outlineVariant = Color(0xFF53433F),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF423734),
    surfaceDim = Color(0xFF1A110F),
    surfaceContainer = Color(0xFF271D1B),
    surfaceContainerHigh = Color(0xFF322825),
    surfaceContainerHighest = Color(0xFF3D322F),
    surfaceContainerLow = Color(0xFF231917),
    surfaceContainerLowest = Color(0xFF140C0A),
)

private val lightRosewood = lightColorScheme(
    primary = Color(0xFF8D4A5C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E0),
    onPrimaryContainer = Color(0xFF703345),
    inversePrimary = Color(0xFFFFB1C4),
    secondary = Color(0xFF75565D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E0),
    onSecondaryContainer = Color(0xFF5B3F46),
    tertiary = Color(0xFF7B5733),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCBF),
    onTertiaryContainer = Color(0xFF60401E),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF22191B),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF22191B),
    surfaceVariant = Color(0xFFF3DDE1),
    onSurfaceVariant = Color(0xFF514346),
    surfaceTint = Color(0xFF8D4A5C),
    inverseSurface = Color(0xFF382E30),
    inverseOnSurface = Color(0xFFFEEDEF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF847376),
    outlineVariant = Color(0xFFD6C2C5),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceDim = Color(0xFFE6D6D8),
    surfaceContainer = Color(0xFFFBEAEC),
    surfaceContainerHigh = Color(0xFFF5E4E6),
    surfaceContainerHighest = Color(0xFFEFDFE1),
    surfaceContainerLow = Color(0xFFFFF0F2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkRosewood = darkColorScheme(
    primary = Color(0xFFFFB1C4),
    onPrimary = Color(0xFF551D2F),
    primaryContainer = Color(0xFF703345),
    onPrimaryContainer = Color(0xFFFFD9E0),
    inversePrimary = Color(0xFF8D4A5C),
    secondary = Color(0xFFE3BDC4),
    onSecondary = Color(0xFF43292F),
    secondaryContainer = Color(0xFF5B3F46),
    onSecondaryContainer = Color(0xFFFFD9E0),
    tertiary = Color(0xFFEDBD92),
    onTertiary = Color(0xFF472A0A),
    tertiaryContainer = Color(0xFF60401E),
    onTertiaryContainer = Color(0xFFFFDCBF),
    background = Color(0xFF191113),
    onBackground = Color(0xFFEFDFE1),
    surface = Color(0xFF191113),
    onSurface = Color(0xFFEFDFE1),
    surfaceVariant = Color(0xFF514346),
    onSurfaceVariant = Color(0xFFD6C2C5),
    surfaceTint = Color(0xFFFFB1C4),
    inverseSurface = Color(0xFFEFDFE1),
    inverseOnSurface = Color(0xFF382E30),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9E8C8F),
    outlineVariant = Color(0xFF514346),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF413738),
    surfaceDim = Color(0xFF191113),
    surfaceContainer = Color(0xFF261D1F),
    surfaceContainerHigh = Color(0xFF312829),
    surfaceContainerHighest = Color(0xFF3C3234),
    surfaceContainerLow = Color(0xFF22191B),
    surfaceContainerLowest = Color(0xFF140C0E),
)

private val lightSakura = lightColorScheme(
    primary = Color(0xFF8C4A5D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E1),
    onPrimaryContainer = Color(0xFF703346),
    inversePrimary = Color(0xFFFFB1C4),
    secondary = Color(0xFF75565D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E1),
    onSecondaryContainer = Color(0xFF5B3F46),
    tertiary = Color(0xFF7B5734),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCBF),
    onTertiaryContainer = Color(0xFF61401E),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF22191B),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF22191B),
    surfaceVariant = Color(0xFFF3DDE1),
    onSurfaceVariant = Color(0xFF514346),
    surfaceTint = Color(0xFF8C4A5D),
    inverseSurface = Color(0xFF382E30),
    inverseOnSurface = Color(0xFFFEEDEF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF847376),
    outlineVariant = Color(0xFFD6C2C5),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceDim = Color(0xFFE6D6D8),
    surfaceContainer = Color(0xFFFBEAEC),
    surfaceContainerHigh = Color(0xFFF5E4E6),
    surfaceContainerHighest = Color(0xFFEFDFE1),
    surfaceContainerLow = Color(0xFFFFF0F2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkSakura = darkColorScheme(
    primary = Color(0xFFFFB1C4),
    onPrimary = Color(0xFF551D2F),
    primaryContainer = Color(0xFF703346),
    onPrimaryContainer = Color(0xFFFFD9E1),
    inversePrimary = Color(0xFF8C4A5D),
    secondary = Color(0xFFE3BDC5),
    onSecondary = Color(0xFF422930),
    secondaryContainer = Color(0xFF5B3F46),
    onSecondaryContainer = Color(0xFFFFD9E1),
    tertiary = Color(0xFFEEBD92),
    onTertiary = Color(0xFF472A0A),
    tertiaryContainer = Color(0xFF61401E),
    onTertiaryContainer = Color(0xFFFFDCBF),
    background = Color(0xFF191113),
    onBackground = Color(0xFFEFDFE1),
    surface = Color(0xFF191113),
    onSurface = Color(0xFFEFDFE1),
    surfaceVariant = Color(0xFF514346),
    onSurfaceVariant = Color(0xFFD6C2C5),
    surfaceTint = Color(0xFFFFB1C4),
    inverseSurface = Color(0xFFEFDFE1),
    inverseOnSurface = Color(0xFF382E30),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9E8C8F),
    outlineVariant = Color(0xFF514346),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF413739),
    surfaceDim = Color(0xFF191113),
    surfaceContainer = Color(0xFF261D1F),
    surfaceContainerHigh = Color(0xFF312829),
    surfaceContainerHighest = Color(0xFF3C3234),
    surfaceContainerLow = Color(0xFF22191B),
    surfaceContainerLowest = Color(0xFF140C0E),
)

private val lightIndigo = lightColorScheme(
    primary = Color(0xFF5C5891),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE3DFFF),
    onPrimaryContainer = Color(0xFF444078),
    inversePrimary = Color(0xFFC5C0FF),
    secondary = Color(0xFF5E5C71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE4DFF9),
    onSecondaryContainer = Color(0xFF464559),
    tertiary = Color(0xFF7B5267),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E9),
    onTertiaryContainer = Color(0xFF603B4F),
    background = Color(0xFFFCF8FF),
    onBackground = Color(0xFF1C1B20),
    surface = Color(0xFFFCF8FF),
    onSurface = Color(0xFF1C1B20),
    surfaceVariant = Color(0xFFE5E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    surfaceTint = Color(0xFF5C5891),
    inverseSurface = Color(0xFF313036),
    inverseOnSurface = Color(0xFFF3EFF7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF787680),
    outlineVariant = Color(0xFFC8C5D0),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8FF),
    surfaceDim = Color(0xFFDCD8E0),
    surfaceContainer = Color(0xFFF0ECF4),
    surfaceContainerHigh = Color(0xFFEBE7EF),
    surfaceContainerHighest = Color(0xFFE5E1E9),
    surfaceContainerLow = Color(0xFFF6F2FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkIndigo = darkColorScheme(
    primary = Color(0xFFC5C0FF),
    onPrimary = Color(0xFF2D2960),
    primaryContainer = Color(0xFF444078),
    onPrimaryContainer = Color(0xFFE3DFFF),
    inversePrimary = Color(0xFF5C5891),
    secondary = Color(0xFFC7C4DC),
    onSecondary = Color(0xFF302E42),
    secondaryContainer = Color(0xFF464559),
    onSecondaryContainer = Color(0xFFE4DFF9),
    tertiary = Color(0xFFEBB9D0),
    onTertiary = Color(0xFF472538),
    tertiaryContainer = Color(0xFF603B4F),
    onTertiaryContainer = Color(0xFFFFD8E9),
    background = Color(0xFF131318),
    onBackground = Color(0xFFE5E1E9),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFE5E1E9),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC8C5D0),
    surfaceTint = Color(0xFFC5C0FF),
    inverseSurface = Color(0xFFE5E1E9),
    inverseOnSurface = Color(0xFF313036),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF928F99),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3A383F),
    surfaceDim = Color(0xFF131318),
    surfaceContainer = Color(0xFF201F25),
    surfaceContainerHigh = Color(0xFF2A292F),
    surfaceContainerHighest = Color(0xFF35343A),
    surfaceContainerLow = Color(0xFF1C1B20),
    surfaceContainerLowest = Color(0xFF0E0E13),
)

private val lightVioletVivid = lightColorScheme(
    primary = Color(0xFF6920FF),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE8DEFF),
    onPrimaryContainer = Color(0xFF4F00D0),
    inversePrimary = Color(0xFFCDBDFF),
    secondary = Color(0xFF6A5779),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF1DAFF),
    onSecondaryContainer = Color(0xFF514060),
    tertiary = Color(0xFF78517B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD5FF),
    onTertiaryContainer = Color(0xFF5E3962),
    background = Color(0xFFFDF7FF),
    onBackground = Color(0xFF1D1A24),
    surface = Color(0xFFFDF7FF),
    onSurface = Color(0xFF1D1A24),
    surfaceVariant = Color(0xFFE7DFF2),
    onSurfaceVariant = Color(0xFF494553),
    surfaceTint = Color(0xFF6920FF),
    inverseSurface = Color(0xFF322F3A),
    inverseOnSurface = Color(0xFFF5EEFD),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF7A7585),
    outlineVariant = Color(0xFFCAC4D5),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFDF7FF),
    surfaceDim = Color(0xFFDED7E6),
    surfaceContainer = Color(0xFFF2EBFA),
    surfaceContainerHigh = Color(0xFFECE5F4),
    surfaceContainerHighest = Color(0xFFE6E0EF),
    surfaceContainerLow = Color(0xFFF8F1FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkVioletVivid = darkColorScheme(
    primary = Color(0xFFCDBDFF),
    onPrimary = Color(0xFF370096),
    primaryContainer = Color(0xFF4F00D0),
    onPrimaryContainer = Color(0xFFE8DEFF),
    inversePrimary = Color(0xFF6920FF),
    secondary = Color(0xFFD5BEE5),
    onSecondary = Color(0xFF3A2948),
    secondaryContainer = Color(0xFF514060),
    onSecondaryContainer = Color(0xFFF1DAFF),
    tertiary = Color(0xFFE7B7E8),
    onTertiary = Color(0xFF46234A),
    tertiaryContainer = Color(0xFF5E3962),
    onTertiaryContainer = Color(0xFFFFD5FF),
    background = Color(0xFF14121C),
    onBackground = Color(0xFFE6E0EF),
    surface = Color(0xFF14121C),
    onSurface = Color(0xFFE6E0EF),
    surfaceVariant = Color(0xFF494553),
    onSurfaceVariant = Color(0xFFCAC4D5),
    surfaceTint = Color(0xFFCDBDFF),
    inverseSurface = Color(0xFFE6E0EF),
    inverseOnSurface = Color(0xFF322F3A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF948E9F),
    outlineVariant = Color(0xFF494553),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3B3743),
    surfaceDim = Color(0xFF14121C),
    surfaceContainer = Color(0xFF211E29),
    surfaceContainerHigh = Color(0xFF2B2833),
    surfaceContainerHighest = Color(0xFF36333E),
    surfaceContainerLow = Color(0xFF1D1A24),
    surfaceContainerLowest = Color(0xFF0F0D17),
)

private val lightGraphite = lightColorScheme(
    primary = Color(0xFF575F6B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDBE3F1),
    onPrimaryContainer = Color(0xFF404753),
    inversePrimary = Color(0xFFBFC7D5),
    secondary = Color(0xFF5A5F66),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDFE2EB),
    onSecondaryContainer = Color(0xFF43474E),
    tertiary = Color(0xFF545F70),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD7E3F8),
    onTertiaryContainer = Color(0xFF3C4858),
    background = Color(0xFFFBF9FA),
    onBackground = Color(0xFF1B1B1D),
    surface = Color(0xFFFBF9FA),
    onSurface = Color(0xFF1B1B1D),
    surfaceVariant = Color(0xFFE4E2E3),
    onSurfaceVariant = Color(0xFF474648),
    surfaceTint = Color(0xFF575F6B),
    inverseSurface = Color(0xFF303031),
    inverseOnSurface = Color(0xFFF3F0F1),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF787778),
    outlineVariant = Color(0xFFC8C6C7),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFBF9FA),
    surfaceDim = Color(0xFFDCD9DB),
    surfaceContainer = Color(0xFFF0EDEE),
    surfaceContainerHigh = Color(0xFFEAE7E9),
    surfaceContainerHighest = Color(0xFFE4E2E3),
    surfaceContainerLow = Color(0xFFF5F3F4),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkGraphite = darkColorScheme(
    primary = Color(0xFFBFC7D5),
    onPrimary = Color(0xFF29313C),
    primaryContainer = Color(0xFF404753),
    onPrimaryContainer = Color(0xFFDBE3F1),
    inversePrimary = Color(0xFF575F6B),
    secondary = Color(0xFFC3C6CF),
    onSecondary = Color(0xFF2C3137),
    secondaryContainer = Color(0xFF43474E),
    onSecondaryContainer = Color(0xFFDFE2EB),
    tertiary = Color(0xFFBBC7DB),
    onTertiary = Color(0xFF263141),
    tertiaryContainer = Color(0xFF3C4858),
    onTertiaryContainer = Color(0xFFD7E3F8),
    background = Color(0xFF131314),
    onBackground = Color(0xFFE4E2E3),
    surface = Color(0xFF131314),
    onSurface = Color(0xFFE4E2E3),
    surfaceVariant = Color(0xFF474648),
    onSurfaceVariant = Color(0xFFC8C6C7),
    surfaceTint = Color(0xFFBFC7D5),
    inverseSurface = Color(0xFFE4E2E3),
    inverseOnSurface = Color(0xFF303031),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF919092),
    outlineVariant = Color(0xFF474648),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF39393A),
    surfaceDim = Color(0xFF131314),
    surfaceContainer = Color(0xFF1F1F21),
    surfaceContainerHigh = Color(0xFF2A2A2B),
    surfaceContainerHighest = Color(0xFF353536),
    surfaceContainerLow = Color(0xFF1B1B1D),
    surfaceContainerLowest = Color(0xFF0E0E0F),
)

private val lightMonochrome = lightColorScheme(
    primary = Color(0xFF000000),
    onPrimary = Color(0xFFE2E2E2),
    primaryContainer = Color(0xFF3B3B3B),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFFC6C6C6),
    secondary = Color(0xFF5E5E5E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD4D4D4),
    onSecondaryContainer = Color(0xFF1B1B1B),
    tertiary = Color(0xFF3B3B3B),
    onTertiary = Color(0xFFE2E2E2),
    tertiaryContainer = Color(0xFF747474),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF9F9F9),
    onBackground = Color(0xFF1B1B1B),
    surface = Color(0xFFF9F9F9),
    onSurface = Color(0xFF1B1B1B),
    surfaceVariant = Color(0xFFE2E2E2),
    onSurfaceVariant = Color(0xFF474747),
    surfaceTint = Color(0xFF5E5E5E),
    inverseSurface = Color(0xFF303030),
    inverseOnSurface = Color(0xFFF1F1F1),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF777777),
    outlineVariant = Color(0xFFC6C6C6),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF9F9F9),
    surfaceDim = Color(0xFFDADADA),
    surfaceContainer = Color(0xFFEEEEEE),
    surfaceContainerHigh = Color(0xFFE8E8E8),
    surfaceContainerHighest = Color(0xFFE2E2E2),
    surfaceContainerLow = Color(0xFFF3F3F3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkMonochrome = darkColorScheme(
    primary = Color(0xFFFFFFFF),
    onPrimary = Color(0xFF1B1B1B),
    primaryContainer = Color(0xFFD4D4D4),
    onPrimaryContainer = Color(0xFF000000),
    inversePrimary = Color(0xFF5E5E5E),
    secondary = Color(0xFFC6C6C6),
    onSecondary = Color(0xFF1B1B1B),
    secondaryContainer = Color(0xFF474747),
    onSecondaryContainer = Color(0xFFE2E2E2),
    tertiary = Color(0xFFE2E2E2),
    onTertiary = Color(0xFF1B1B1B),
    tertiaryContainer = Color(0xFF919191),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF131313),
    onBackground = Color(0xFFE2E2E2),
    surface = Color(0xFF131313),
    onSurface = Color(0xFFE2E2E2),
    surfaceVariant = Color(0xFF474747),
    onSurfaceVariant = Color(0xFFC6C6C6),
    surfaceTint = Color(0xFFC6C6C6),
    inverseSurface = Color(0xFFE2E2E2),
    inverseOnSurface = Color(0xFF303030),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF919191),
    outlineVariant = Color(0xFF474747),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF393939),
    surfaceDim = Color(0xFF131313),
    surfaceContainer = Color(0xFF1F1F1F),
    surfaceContainerHigh = Color(0xFF2A2A2A),
    surfaceContainerHighest = Color(0xFF353535),
    surfaceContainerLow = Color(0xFF1B1B1B),
    surfaceContainerLowest = Color(0xFF0E0E0E),
)

private val lightContrastBlue = lightColorScheme(
    primary = Color(0xFF073764),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF4A6F9F),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFFA4C9FE),
    secondary = Color(0xFF2C3747),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF636E80),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF432E4C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF7C6586),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFF8F9FF),
    onBackground = Color(0xFF0F1116),
    surface = Color(0xFFF8F9FF),
    onSurface = Color(0xFF0F1116),
    surfaceVariant = Color(0xFFDFE2EB),
    onSurfaceVariant = Color(0xFF32363D),
    surfaceTint = Color(0xFF3B608F),
    inverseSurface = Color(0xFF2E3035),
    inverseOnSurface = Color(0xFFEFF0F7),
    error = Color(0xFF740006),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFCF2C27),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFF4F535A),
    outlineVariant = Color(0xFF696D75),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF8F9FF),
    surfaceDim = Color(0xFFC5C6CC),
    surfaceContainer = Color(0xFFE7E8EE),
    surfaceContainerHigh = Color(0xFFDBDCE3),
    surfaceContainerHighest = Color(0xFFD0D1D8),
    surfaceContainerLow = Color(0xFFF2F3FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

private val darkContrastBlue = darkColorScheme(
    primary = Color(0xFFC9DEFF),
    onPrimary = Color(0xFF00264B),
    primaryContainer = Color(0xFF6F93C5),
    onPrimaryContainer = Color(0xFF000000),
    inversePrimary = Color(0xFF224977),
    secondary = Color(0xFFD2DDF2),
    onSecondary = Color(0xFF1B2636),
    secondaryContainer = Color(0xFF8691A4),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFFF0D3F9),
    onTertiary = Color(0xFF311E3B),
    tertiaryContainer = Color(0xFFA188AB),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF111318),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF43474E),
    onSurfaceVariant = Color(0xFFD9DCE5),
    surfaceTint = Color(0xFFA4C9FE),
    inverseSurface = Color(0xFFE1E2E9),
    inverseOnSurface = Color(0xFF282A2F),
    error = Color(0xFFFFD2CC),
    onError = Color(0xFF540003),
    errorContainer = Color(0xFFFF5449),
    onErrorContainer = Color(0xFF000000),
    outline = Color(0xFFAFB2BB),
    outlineVariant = Color(0xFF8D9099),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF42444A),
    surfaceDim = Color(0xFF111318),
    surfaceContainer = Color(0xFF25282D),
    surfaceContainerHigh = Color(0xFF303338),
    surfaceContainerHighest = Color(0xFF3B3E43),
    surfaceContainerLow = Color(0xFF1B1E22),
    surfaceContainerLowest = Color(0xFF05070B),
)

/** 静态色板查表。[ThemeMode.FOLLOW_WALLPAPER] 不在此表中，由调用方走动态取色。 */
private val STATIC_SCHEMES: Map<String, Pair<ColorScheme, ColorScheme>> = mapOf(
    "jxau-blue" to (lightJxauBlue to darkJxauBlue),
    "lake-cyan" to (lightLakeCyan to darkLakeCyan),
    "celadon" to (lightCeladon to darkCeladon),
    "bamboo" to (lightBamboo to darkBamboo),
    "amber" to (lightAmber to darkAmber),
    "coral" to (lightCoral to darkCoral),
    "rosewood" to (lightRosewood to darkRosewood),
    "sakura" to (lightSakura to darkSakura),
    "indigo" to (lightIndigo to darkIndigo),
    "violet-vivid" to (lightVioletVivid to darkVioletVivid),
    "graphite" to (lightGraphite to darkGraphite),
    "monochrome" to (lightMonochrome to darkMonochrome),
    "contrast-blue" to (lightContrastBlue to darkContrastBlue),
)

/**
 * 取某个主题的配色。返回 null 表示该主题要用动态取色（Android 12+）。
 *
 * 调用示例（见 ui/theme/AppTheme.kt）：
 * ```
 * val theme = THEME_CATALOG.firstOrNull { it.id == selectedId } ?: THEME_CATALOG.first()
 * val scheme = theme.staticScheme(dark = isSystemInDarkTheme())
 *     ?: if (isSystemInDarkTheme()) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
 * ```
 */
fun AppTheme.staticScheme(dark: Boolean): ColorScheme? {
    val pair = STATIC_SCHEMES[id] ?: return null
    return if (dark) pair.second else pair.first
}
